export default {
  FIELD_GROUP:         'FIELD_GROUP',
  UPDATE_FIELD_GROUPS: 'UPDATE_FIELD_GROUPS',
  UPDATE_FIELD_GROUP:  'UPDATE_FIELD_GROUP',
  PUSH_PUBLIC_AREA:    'PUSH_PUBLIC_AREA',
  EDIT_PUBLIC_AREA:    'EDIT_PUBLIC_AREA',
  REMOVE_PUBLIC_AREA:  'REMOVE_PUBLIC_AREA'
}
