export default {
  FIELD_GROUP:           'FIELD_GROUP',
  TOGGLE_MAPPING_STATUS: 'TOGGLE_MAPPING_STATUS',
  UPDATE_FIELD_GROUPS:   'UPDATE_FIELD_GROUPS',
  UPDATE_FIELD_GROUP:    'UPDATE_FIELD_GROUP',
  PUSH_PUBLIC_AREA:      'PUSH_PUBLIC_AREA',
  EDIT_PUBLIC_AREA:      'EDIT_PUBLIC_AREA',
  REMOVE_PUBLIC_AREA:    'REMOVE_PUBLIC_AREA',
  PUSH_LOCATION:         'PUSH_LOCATION',
  EDIT_LOCATION:         'EDIT_LOCATION',
  REMOVE_LOCATION:       'REMOVE_LOCATION',
  UPDATE_CENSUS:         'UPDATE_CENSUS'
};
